[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    urls = ["/recipes/authentic-italian-alfredo-sauce-recipe#wprm-recipe-container-2230"]
    output_path = "reports/lighthouse.html"
