[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    urls = [ "https://staging.piattorecipes.com/recipes/authentic-italian-alfredo-sauce-recipe" ]
    output_path = "reports/lighthouse.html"
