[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    audit_url = "https://staging.piattorecipes.com/recipes/authentic-italian-alfredo-sauce-recipe"
    output_path = "reports/lighthouse.html"
